In [2]:
import numpy as np

In [7]:
s = np.array(5)
print(s.ndim)
print(s.shape)
print("========")
v = np.array([1, 2, 3])
print(v.ndim)
print(v.shape)
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]
              ])
print("========")
print(m.ndim)
print(m.shape)

0
()
1
(3,)
2
(3, 3)


In [8]:
vec_1 = np.array([1, 2, 3, 4,5,6])

vec_2 = vec_1.reshape(3, 2)
print(vec_1)
print(vec_2)


[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [10]:
vec_2 = np.array([1, 2, 3 , 4, 5 ,6 ,7,8])
mat_2 = vec_2.reshape((vec_2.shape[0],1))
mat_2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [11]:
vec_2[:,None]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [15]:
mat = np.array([[0.1, True, o1],
                [4, 5, 6],
                [7, 8, 9]
                ])
mat.dtype

dtype('O')

In [18]:
mat = np.array([[0.1, True, 'hag'],
                [4, 5, 6],
                [7, 8, 9]
                ])
print(mat.dtype)
print(mat)

<U32
[['0.1' 'True' 'hag']
 ['4' '5' '6']
 ['7' '8' '9']]


In [14]:
class c :
    x=3
o1 = c()    

In [24]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [0,0,0]
                ])
mat[-3:-1,-3:-1]

array([[4, 5],
       [7, 8]])

In [22]:
vec_1 = np.array([1, 2, 3, 4,5,6])
vec_1[-3:-1]

array([4, 5])

In [25]:
transposed = mat.T
transposed

array([[1, 4, 7, 0],
       [2, 5, 8, 0],
       [3, 6, 9, 0]])

In [29]:
mat = np.arange(0,361,90)
mat

array([  0,  90, 180, 270, 360])

In [3]:
mat_1 = np.ones((3,4))
mat_2 = np.zeros((3,4))

In [4]:
np.savez('test.npz', ones_mat = mat_1 , zeros_mat = mat_2)

In [5]:
with np.load('test.npz') as file:
    mat_1 = file['ones_mat']
    mat_2 = file['zeros_mat']
print(mat_1)    

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
m1 = np.array([[1,2,3],
               [0,0,0]
               
               ])
m2 = np.array([[4,5,6],
               [0,0,0]
               
               ])
vert_mat = np.vstack((m1,m2))
vert_mat = np.hstack((m1,m2))
vert_mat

array([[1, 2, 3],
       [0, 0, 0],
       [4, 5, 6],
       [0, 0, 0]])

In [7]:
s = 5
v = np.array([ 2, 4 , 3 ,4 , 10])
v == s

array([False, False, False, False, False])

In [9]:
v = np.array([ 1 ,2, 4 , 5 , 0])
np.any(v>2)

np.True_

In [11]:
v1 = np.array([ 2, 4 , 3 ,4 , 10])
v2 = np.array([ 1 ,2, 4 , 5 , 0])
np.isclose(v1,v2, atol=1)

array([ True, False,  True,  True, False])

In [10]:
v = np.array([ 2, 4 , 3 ,4 , 10])
condition = v>=4
cond_access = v[condition]
cond_access

array([ 4,  4, 10])